import "./src/styles/normalize.css"
import "jquery/dist/jquery.min.js"
import "popper.js/dist/popper.min"
import "bootstrap/dist/js/bootstrap.min.js"
import "./src/styles/global.css"
import "./node_modules/@fortawesome/fontawesome-free/css/all.css"
import "./node_modules/plyr/dist/plyr.css"
